syntax on
filetype plugin on

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" Highlight matching brace
set showmatch

" Highlight all search results
set hlsearch

" Add the 80-symbols marker
set colorcolumn=80

